### ISSUE TITLE
Custom formatters functionality does not seem to be active 

### ISSUE THREAD

**Issue by Gregg8** [binaryage/cljs-devtools#18]
I am getting this warning message in the console (have just updated to `0.7.0`):

`"Custom formatters functionality does not seem to be active in your DevTools..."`

I definitely have it checked. In fact, the installation message proves that:

`"Installing CLJS DevTools 0.7.0 and enabling features :custom-formatters :sanity-hints"`

I have tested this behaviour in Windows Chrome `51.0.2704.84 m` and Canary `53.0.2768.0` (Canary doesn't display the warning but still fails to show my lovely formatted data)

However, in all cases, if I simply refresh the browser, it initialises properly and I see formatted data.

I then went back to `0.6.0` and experienced the same behaviour. Didn't go back any further.

**Comment by darwin** [comment]
First, the installation message does not prove that you have "custom formatters" enabled in your DevTools.  It just tells you that your cljs code called `devtools.core/install!`.

Second, unfortunately custom formatters are not applied while console is not opened. So if you open console after logging some rich data using custom formatters you have to refresh the page for logging to happen with open console.

I should probably improve the warning message, and inform user about this behaviour, because right now it is misleading.

**Comment by Gregg8** [comment]
Ok, thanks for clarifying about the installation message and about Devtools needing to be opened for the formatters to start operating.

I'm still puzzled why that message would have appeared, even though I definitely had the option checked. 

On further experimentation, it appears to intermittent, and will appear if I have DevTools closed or if I am quick enough to open DevTools before the message has appeared.

**Comment by darwin** [comment]
I point to this FAQ item:
https://github.com/binaryage/cljs-devtools/blob/master/docs/faq.md#why-some-custom-formatters-were-not-rendered

suggestions for improvements welcome

**Comment by Gregg8** [comment]
Thanks, that explanation is clear and gives us the option to disable it the warning.
