### ISSUE TITLE
TypeError: target.addEventListener is not a function

### ISSUE THREAD

**Issue by metehan** [binaryage/cljs-devtools#53]
CLJS DevTools Error target.addEventListener is not a function

```
 TypeError: target.addEventListener is not a function
    at listen (events.js:68)
    at Feature.handleGeometryChanged_ (Feature.js:282)
    at Feature.Target.dispatchEvent (Target.js:162)
    at Feature.BaseObject.notify (Object.js:212)
    at Feature.BaseObject.set (Object.js:233)
    at Feature.BaseObject.setProperties (Object.js:248)
    at new Feature (Feature.js:167)
    at Object.tools$mapping$add_route [as add_route] (mapping.cljs:55)
    at mapping.cljs:63
    at Object.sval (core.cljs:3422) 

---
Please report the issue here: https://github.com/binaryage/cljs-devtools/issues
```

What other information will be needed to report the bug properly?

**Comment by darwin** [comment]
I don't understand the stack trace. But internal errors are reported when CLJS devtools tries to format a given value and the [code throws for some reason](https://github.com/binaryage/cljs-devtools/blob/7ace48cf25b89e3d3c37d99b623fa274a5d45c0f/src/lib/devtools/formatters/core.cljs#L66). 

In general there could be two possible cases. The exception was raised from CLJS devtools code due to a bug. Or the exception was raised from user's code when CLJS devtools tried to do something (e.g. by calling cljs pritning protocols).

In this case it looks like your code raised the exception. If you look at [Object.sval](https://github.com/clojure/clojurescript/blob/0c353f1947089cb8b1f010b4294b94ac109d4ef6/src/main/cljs/cljs/core.cljs#L3422) in core.cljs. It is part of LazySeq. My guess is that CLJS devtools tried to print some items in your lazy sequence and your code raised exception during realization of the sequence. The stack trace you got/pasted is incomplete for some reason.
