### ISSUE TITLE
Custom formatters are being removed from Chrome?

### ISSUE THREAD

**Issue by tekacs** [binaryage/cljs-devtools#55]
Chrome seems to have changed the setting for loading custom formatters, now (I'm using Chrome 84.0.4143.7).

Instead of 'Enable custom formatters', it's now called ['Temporarily enable deprecated custom formatters'][1].

The corresponding commit in Chrome DevTools included the comment:
[`TODO(1016755): remove custom formatters altogether.`][2]
which leads me to the Chrome bug petitioning to remove them altogether:

https://bugs.chromium.org/p/chromium/issues/detail?id=1016755

It might be worth chiming in there to petition to keep them, at least until a replacement is provided by the Dart team -- and especially in case it's a massive undertaking to port the current formatters should they remove the existing API...

I wrote a PR to change the cljs-devtools docs, but I wasn't sure if you wanted to include some language to explain to the user what's going on -- and also to let the user know that they're going to have to turn this setting on every time they restart Chrome, now.

[1]: https://github.com/ChromeDevTools/devtools-frontend/blob/a7e5e973577cbd451c43cb04120932486cd9d8aa/front_end/sdk/sdk_strings.grdp#L625

[2]: https://github.com/ChromeDevTools/devtools-frontend/commit/85e196bd4bc68ca7850c458eaa0fb00eb379f3d3#diff-3cf273a40d7f903d23ccccd12a43b157R64

**Comment by darwin** [comment]
I confirm. Thanks for communicating this. PRs to explain this to users are welcome.

Also I got access to the document they mention in [a comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1016755#c3). Unfortnately their plan is to remove it (in M86) without a replacement. But they want to collect user feedback before doing that. Personally, I don't think we can persuade them to keep the feature in current form. CLJS is pretty small community. We have to hope that some other bigger players rely on this and will throw in their weight.

**Comment by darwin** [comment]
Just to add. I think users have to re-enable this feature every time they open the devtools. When they close it, the devtools instance goes away and the setting will be reset next time they open it.

So for a scenario where you have a development session where you keep your devtools opened since starting Chrome you have to do it once per development session which is not that bad IMO.

**Comment by kwrooijen** [comment]
Stumbled upon this today. I was really confused as to why my custom formatter was broken, then I realized the setting automatically disables itself now. Once this feature is removed, `cljs-devtools` will no longer be usable. Are there any ideas on a replacement / solution for the future?

**Comment by darwin** [comment]
One option is to use Dirac, where I reverted the change for now:
https://github.com/binaryage/dirac/commit/4d321af0b6862d6281c60ea35940e726a4556d2b

btw. If you are using macOS, Dirac is not such pain to setup anymore - with the new CLI workflow:
https://github.com/binaryage/dirac

**Comment by kwrooijen** [comment]
Hadn't heard of dirac, thanks for sharing! Going to check out

**Comment by yogthos** [comment]
Has anyone looked if it's possible to get custom formatters to work in Firefox instead?

**Comment by danielcompton** [comment]
> 
Has anyone looked if it's possible to get custom formatters to work in Firefox instead?

I briefly spoke with @codehag about this last year. I think in principle this would be doable, but it would require a lot of work from someone, and it likely wasn’t a high priority for Mozilla to do themselves. I’m not sure how the calculus on accepting this would change if Google is removing it from Chrome. The spec just being a Google doc is also a problem.

**Comment by yogthos** [comment]
Ah, at least it hasn't been rejected.

**Comment by victorb** [comment]
It's been put on hold now, after receiving user feedback. So hope is still there.

https://twitter.com/ChromeDevTools/status/1263428187809251328

Document linked above also includes "This has been put on hold due to user feedback"

**Comment by ArcanisCz** [comment]
FYI, some React developers rely on this feature too, some handy addons like https://chrome.google.com/webstore/detail/immutablejs-object-format/hgldghadipiblonfkkicmgcbbijnpeog

**Comment by hashseed** [comment]
I'm the engineer behind this change. I'd like to give some background.

You will have noticed that the intended removal was planned to be rolled out step by step. The first step being that the experimental setting no longer sticks, and has to be enabled for every DevTools session. We intentionally did not remove the feature at once. Feedback like the one provided here is what we have been looking for, so thank you for that.

As for the rationale for the original proposal: custom formatters are an experimental feature and also not part of any spec, so we were not sure whether it found any significant adoption. Unfortunately, it has a flawed design, which made it a part of several security exploits in the past.

I can see that custom formatters are being relied on. That's why I already reverted the first step. We will reconsider this issue and hopefully can come up with a solution that doesn't break your use case.

**Comment by darwin** [comment]
Thank you very much, @hashseed. I'm ready to promptly rewrite/adapt cljs-devtools for the new solution. Whatever you come up with.

Assuming "a better and safer JSON-ML", I'd suggest to implement the new renderer/subsystem as a separate open-source library decoupled from devtools codebase. This would greatly help porting this functionality to other browsers and to "in-page space". We already have some projects[1][2] which had to reimplement JSON-ML rendering in other contexts because they wanted to reuse cljs-devtools functionality. Other people were interested rendering custom formatters in their own debug tools in-page. Not sure how much effort are you going to spend on it, but this portability would be something to consider.

[1] https://github.com/day8/re-frame-10x
[2] https://github.com/day8/re-frame-10x/blob/8aef576e31277fe15676558eb3841201b815f5cf/src/day8/re_frame_10x/view/components.cljs#L127

**Comment by TimvdLippe** [comment]
Should the changes made in 1.0.1 be reverted now?

**Comment by darwin** [comment]
@TimvdLippe yes, they will be reverted with explanation.

**Comment by darwin** [comment]
I just released [v1.0.2](https://github.com/binaryage/cljs-devtools/releases/tag/v1.0.2) which has the warning removed.

We can still see some reports from people having Chrome version with non-sticky custom formatters and who missed the warning and release note. So I will leave this issue open for a while.

**Comment by hashseed** [comment]
The non-sticky setting is already being rolled out with Canary. But it still needs to be cherry-picked into Chrome 84. Will do this next week.

**Comment by ELLIOTTCABLE** [comment]
I … I … I'm so freaking confused. I see that *now* that I open it (no, Chrome hasn't updated since I commented); but previously, that exact 'settings' button was opening a *completely* different interface; there were no 'tabs' along the left side of the page; and there were a total of about half the total checkboxes/etc visible to me now.

I feel like I'm going insane. Anyway, yes, the option is there now; sorry for wasting your time … o_o;

**Comment by mike-thompson-day8** [comment]
@ELLIOTTCABLE  I wonder ... there are two settings tabs.  One for Chrome itself and one for Devtools.

**Comment by xgqfrms** [comment]
![](https://img2022.cnblogs.com/blog/740516/202204/740516-20220430104646482-2107689277.png)

> settings

![](https://img2022.cnblogs.com/blog/740516/202204/740516-20220430105424745-2015902016.png)

![](https://img2022.cnblogs.com/blog/740516/202204/740516-20220430105327331-744692713.png)

**Comment by mike-thompson-day8** [comment]
![image](https://user-images.githubusercontent.com/3033376/166093712-2dab176c-a3bc-476d-bff7-b49ac80b14dd.png)
